/*
==============================================================================

This file was auto-generated by the Jucer!

It contains the basic startup code for a Juce application.

==============================================================================
*/

#ifndef __PLUGINEDITOR_H_FEBB7173__
#define __PLUGINEDITOR_H_FEBB7173__

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"


//==============================================================================
/**
*/
class SpectralDelayPluginAudioProcessorEditor  : public AudioProcessorEditor, public Slider::Listener
{
public:
	SpectralDelayPluginAudioProcessorEditor (SpectralDelayPluginAudioProcessor&p);
	~SpectralDelayPluginAudioProcessorEditor();

	//==============================================================================
	// This is just a standard Juce paint method...
    void resized() override;
	void paint (Graphics& g)override;
    void sliderValueChanged(Slider* changedSlider)override;

private:
	Label f0_titleLabel;
	Label f1_titleLabel;
	Label f2_titleLabel;
	Label f3_titleLabel;
	Label f4_titleLabel;
	Label logo;
	Label version;

	Slider f0_delaySlider;
	Slider f1_delaySlider;
	Slider f2_delaySlider;
	Slider f3_delaySlider;
	Slider f4_delaySlider;
    SpectralDelayPluginAudioProcessor& processor;

	
//	SpectralDelayPluginAudioProcessor* getProcessor() const
//	{
//		return static_cast<SpectralDelayPluginAudioProcessor*>(getAudioProcessor());
//	}
};


#endif  // __PLUGINEDITOR_H_FEBB7173__
